- name: Cisco ASA fw-web-dns access-list 
  connection: local
  hosts: firewall
  gather_facts: false
  vars:
    cli:
      username: "{{ username }}"
      password: "{{ password }}"
      host: "{{ device_ip }}"
      authorize: yes
      auth_pass: "{{ secret }}"
  tasks:
    - name: create object group
      asa_config:
        lines:
          - network-object host 172.31.0.17
          - network-object host 172.31.0.18
          - network-object host 172.31.0.19
        parents: ['object-group network fe-web-dns-group']
        provider: "{{ cli }}"
      register: result

    - name: configure access-list
      asa_acl:
        lines:
          - access-list acl_inside extended permit tcp object-group fe-web-dns-group any eq www
          - access-list acl_inside extended permit udp object-group fe-web-dns-group any eq domain
          - access-list acl_inside extended deny ip any any
        before: clear configure access-list acl_inside
        match: strict
        replace: block
        provider: "{{ cli }}" 
      register: result # print results var to screen

    - debug: var=result
